[package]
name = "image_squarer"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
image = "0.25.1"
num = "0.4.3"
rfd = "0.14.1"
